Methods
================================================================================

We used BEAM (Behavior, Energy, Autonomy, and Mobility) as our model to run and calibrate our simulations. BEAM is being developed by Lawrence Berkeley National Laboratory and the UC Berkeley Institute for Transportation Studies, and is an extension to the MATSim (Multi-Agent Transportation Simulation) model [@beamdocs]. We created a fork of the main BEAM repository for this and other projects. One aspect of the code we developed is the ability to add geofencing, in which ridehail vehicles are constrained to a specific polygon. The version of the code we used is available at https://github.com/tscore-utc/beam/commit/b28bc396fd50db6099e9aecc54c24642feb4f74d.

As UTA already has a ridehail pilot program underway, we reached out to find the fleet size and shifts for the ridehail vehicles. Shaina Quinn, a researcher at UTA's Office of Innovative Mobility Solutions, informed us that typically 12 ridehail vehicles provide service at a time. We found the shifts on UTA's website for the service [@SLCSouth]. Since we didn't have information on fleet size or shifts for any scenario except the existing pilot program, we used the same values for each additional study area as well.

We first created a base scenario to model the existing pilot program. There were three other areas we wished to analyze for potential ridehail expansion: near the SLC Int'l airport, Sandy, and West Jordan. The area near the airport is planned to get ridehail service beginning December 13, 2021 [@Airport], so we included that area in all scenarios except the base.

We compared the different scenarios on several metrics, including weekday ridership, utilization (passengers/hour/vehicle), wait time, and travel time. We also compared the base scenario to the results of UTA's September 2020 report [@UTAreport]. The results of that report used many qualitative metrics, but some quantitative metrics of interest were average ridership, wait time, and utilization. These results of the report are presented in Table \@ref(tab:UTAOD) below.

```{r UTAOD}
UTAOD <- read_csv("data/UTAODpilotinfo.csv")
UTAODJM <- UTAOD %>% 
  filter(Month %in% c("JAN", "FEB", "MAR"))

UTAOD %<>% 
  add_row(Month = "Average",
          `Avg wkday ridership` = mean(UTAOD$`Avg wkday ridership`),
          Utilization = mean(UTAOD$Utilization),
          `Avg wait time` = mean(UTAOD$`Avg wait time`)
  ) %>% 
  add_row(Month = "Average Jan--Mar",
          `Avg wkday ridership` = mean(UTAODJM$`Avg wkday ridership`),
          Utilization = mean(UTAODJM$Utilization),
          `Avg wait time` = mean(UTAODJM$`Avg wait time`))

UTAOD %>% 
  my_kbl(align = 'lrrr',
         caption = "UTA On Demand Report Findings") %>%
  row_spec((nrow(UTAOD)-1):nrow(UTAOD), bold = T)
```
