---
title: "Something about Microtransit Simulation"
author:
  - name: Hayden Atchley
    email: satchley@byu.edu
    affiliation: Brigham Young University
  - name: Gregory Macfarlane?
    email: bob@example.com
    affiliation: Brigham Young University
address:
  - code: Brigham Young University
    address: Civil and Construction Engineering Department, 430 Engineering Building, Provo, Utah 84602
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: article
journal: "Findings"
bibliography: [references.bib]
biblio-style: apalike
link-citations: yes
abstract: |
 This paper has to do with simulating microtransit and determining whether it makes sense to deploy microtransit in other areas in the Wasatch Front.
description: "A short description"
layout: "3p, authoryear"
keywords:
  - Microtransit
  - Passive Data
  - Location Choice
---

Question
================================================================================

In November of 2019, the Utah Transit Authority (UTA) began a partnership with Via Transportation, a private mobility company [@UTAreport]. Under this partnership, UTA has supplemented its fixed-route services with on-demand shuttles hailed through a mobile application. So-called “microtransit” offerings of this kind have the potential to efficiently extend UTA services into low-density areas and function as first- and last-mile services for the regular fixed-route rail and bus network. The current microtransit service is currently only operating in southern Salt Lake County [@UTAonDemand]. UTA is interested in examining if there are other areas where similar services can be effectively deployed.

In September 2020, UTA released a report detailing a possible expansion of microtransit services to other areas in Utah following the UTA on Demand pilot program [@UTAreport]. 19 zones were identified between Brigham City and Santaquin as areas that could potentially benefit from microtransit services. Ridership was estimated based on number of residents and number of workers employed within each zone, as well as a mode share score that VIA developed based on their internal demand model.

We seek however to provide UTA and the Utah Department of Transportation (UDOT) with a template they can use to examine projects of this kind with a microsimulation model. We want to know how the results of such a model would compare to those of UTA’s September 2020 report. Though that report made no definitive recommendations regarding expansion of microtransit services, it may be useful in calibrating our simulation. We also seek to use our results (possibly in conjunction with those of UTA’s report) to make recommendations to UTA and UDOT regarding expansion of microtransit services.

<!--chapter:end:index.Rmd-->

Methods
================================================================================

Here is what I did

<!--chapter:end:02-methods.Rmd-->

Findings
================================================================================

Here's what I found

<!--chapter:end:03-findings.Rmd-->

Acknowledgements {-}
================================================================================

I would like to thank some people

<!--chapter:end:04-acknowledgements.Rmd-->

`r if (knitr::is_html_output()) '
# References {-}
'`

<!--chapter:end:05-references.Rmd-->

